name: publish

on: [push]

jobs:
  pushing-mysql-5-images:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
      IMAGE_NAME: ghcr.io/thorsager/quick-mysql
      IMAGE_TAG: 8

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build . --build-arg "MYSQL_TAG=${IMAGE_TAG}" --tag "${IMAGE_NAME}:${IMAGE_TAG}"

    - name: Push image 
      run: |
        echo $PAT | docker login ghcr.io -u thorsager --password-stdin
        docker push "${IMAGE_NAME}:${IMAGE_TAG}"

